name: Push Docker Image to ghcr.io from pfannkuchensack-dev
on:
  push:
    branches: [ "pfannkuchensack-dev" ]
jobs:
  build:
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        gpu-driver:
        - cuda
    runs-on: ubuntu-latest
    name: ${{ matrix.gpu-driver }}
    env:
      PLATFORMS: 'linux/amd64'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=sha
    - name: Build container
      timeout-minutes: 40
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile
        platforms: ${{ env.PLATFORMS }}
        build-args: |
          GPU_DRIVER=${{ matrix.gpu-driver }}
        push: ${{ github.ref == 'refs/heads/pfannkuchensack-dev' }}
        tags: ${{ steps.meta.outputs.tags }}
        # cache-from: |
        #   type=gha,scope=${{ github.ref_name }}-${{ matrix.gpu-driver }}
        #   type=gha,scope=main-${{ matrix.gpu-driver }}
        # cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-${{ matrix.gpu-driver }}
